AWSTemplateFormatVersion: "2010-09-09"
Resources:
  PentagonLambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: S3FullAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 's3:*'
                Resource: 'arn:aws:s3:::pentagon-s3-bucket/*'

  PentagonGuestUserGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: "PentagonGuestUserGroup"

  PentagonGuestIAMUser1:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "PentagonGuestYudaisugiyama"
      Groups:
        - !Ref PentagonGuestUserGroup

  PentagonGuestIAMUser2:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "PentagonGuestYusei53"
      Groups:
        - !Ref PentagonGuestUserGroup

  PentagonGuestIAMUser3:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "PentagonGuestUmaidashi"
      Groups:
        - !Ref PentagonGuestUserGroup

  PentagonGuestIAMUser4:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "PentagonGuestNajah"
      Groups:
        - !Ref PentagonGuestUserGroup

  PentagonGuestUser1AccessKey:
    Type: "AWS::IAM::AccessKey"
    Properties:
      UserName: !Ref PentagonGuestIAMUser1

  PentagonGuestUser2AccessKey:
    Type: "AWS::IAM::AccessKey"
    Properties:
      UserName: !Ref PentagonGuestIAMUser2

  PentagonGuestUser3AccessKey:
    Type: "AWS::IAM::AccessKey"
    Properties:
      UserName: !Ref PentagonGuestIAMUser3
  
  PentagonGuestUser4AccessKey:
    Type: "AWS::IAM::AccessKey"
    Properties:
      UserName: !Ref PentagonGuestIAMUser4
  
  PentagonGuestUserPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "PentagonGuestUserPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:*"
            Resource: "*"
          - Effect: "Allow"
            Action:
              - "dynamodb:*"
            Resource: "*"
          - Effect: "Allow"
            Action:
              - "lambda:*"
            Resource: "*"
          - Effect: "Allow"
            Action:
              - "apigateway:*"
            Resource: "*"
          - Effect: "Allow"
            Action:
              - "iam:ListRoles"
              - "iam:PassRole"
            Resource: "*"
      Groups:
        - !Ref PentagonGuestUserGroup